// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Dataaccess.Server;

#nullable disable

namespace Project.Dataaccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250111090245_UpdateProductModel")]
    partial class UpdateProductModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("project.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListPrice")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Price100")
                        .HasColumnType("int");

                    b.Property<int>("Price50")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Vinay",
                            CategoryId = 1,
                            Description = "Fortune Time is a three-reel, nine-line mechanical slot game by Everi that involves searching for hidden treasures",
                            ISBN = "SWD98320284",
                            ImageUrl = "",
                            ListPrice = 99,
                            Price = 90,
                            Price100 = 80,
                            Price50 = 85,
                            Title = "Fortune of time"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Deepak",
                            CategoryId = 1,
                            Description = "this novel is considered a classic and explores themes of class, gender, and tragedy.",
                            ISBN = "SWD98322344",
                            ImageUrl = "",
                            ListPrice = 120,
                            Price = 110,
                            Price100 = 100,
                            Price50 = 105,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mayur",
                            CategoryId = 2,
                            Description = "this book is considered an English classic and tells the story of a man in search of truth.",
                            ISBN = "SWD45320284",
                            ImageUrl = "",
                            ListPrice = 150,
                            Price = 145,
                            Price100 = 130,
                            Price50 = 140,
                            Title = "The Pilgrim's Progress"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Saurabh",
                            CategoryId = 3,
                            Description = "this novel is considered a complex literary confection.",
                            ISBN = "SWD9832684",
                            ImageUrl = "",
                            ListPrice = 200,
                            Price = 195,
                            Price100 = 170,
                            Price50 = 180,
                            Title = "Robinson Crusoe"
                        });
                });

            modelBuilder.Entity("project.Models.Product", b =>
                {
                    b.HasOne("project.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
